name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt update && sudo apt install -y clang cmake libc++-dev libc++abi-dev libsqlite3-dev

      - run: |
          mkdir build
          cd build
          export CC=clang
          export CXX=clang++
          cmake -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-stdlib=libc++" ..
          make -j4

      - uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/endstone_tianyan.so
